name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  ubuntu20_base:
    name: Push Ubuntu20 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ secrets.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu20-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu22_base:
    name: Push Ubuntu22 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ secrets.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  ubuntu20-g4-10-7:
    needs: [ubuntu20_base]
    name: Push Ubuntu20 g4.10.7 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ secrets.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu20-g4.10.7

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu20-g4.10.7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
  ubuntu22-g4-10-7:
    needs: [ubuntu22_base]  
    name: Push Ubuntu22 g4.10.7 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ secrets.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-g4.10.7

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-g4.10.7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}