name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  ubuntu20_base:
    name: Push Ubuntu20 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check username
        run: |
          echo ${{ vars.BOOGERT_DOCKER_USERNAME }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu20-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu20-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu22_base:
    name: Push Ubuntu22 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  centos7_base:
    name: Push centos7 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check username
        run: |
          echo ${{ vars.BOOGERT_DOCKER_USERNAME }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/centos7-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/centos7-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  centos8_base:
    name: Push centos8 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check username
        run: |
          echo ${{ vars.BOOGERT_DOCKER_USERNAME }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/centos8-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/centos8-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  alma9_base:
    name: Push Alma9 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check username
        run: |
          echo ${{ vars.BOOGERT_DOCKER_USERNAME }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/alma9-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/alma9-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu20-g4-10-7:
    needs: [ubuntu20_base]
    name: Push Ubuntu20 g4.10.7 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu20-g4.10.7

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu20-g4.10.7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu20-g4-11-0:
    needs: [ubuntu20_base]
    name: Push Ubuntu20 g4.11.0 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu20-g4.11.0

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu20-g4.11.0
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu20-g4-11-1:
    needs: [ubuntu20_base]
    name: Push Ubuntu20 g4.11.1 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu20-g4.11.1

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu20-g4.11.1
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu20-g4-11-2:
    needs: [ubuntu20_base]
    name: Push Ubuntu20 g4.11.1 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu20-g4.11.2

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu20-g4.11.2
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu22-g4-10-7:
    needs: [ubuntu22_base]  
    name: Push Ubuntu22 g4.10.7 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-g4.10.7

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-g4.10.7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu22-g4-11-0:
    needs: [ubuntu22_base]
    name: Push Ubuntu22 g4.11.0 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-g4.11.0

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-g4.11.0
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu22-g4-11-1:
    needs: [ubuntu22_base]
    name: Push Ubuntu22 g4.11.1 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-g4.11.1

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-g4.11.1
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ubuntu22-g4-11-2:
    needs: [ubuntu22_base]
    name: Push Ubuntu22 g4.11.2 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-g4.11.2

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-g4.11.2
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  alma9-g4-10-7:
    needs: [alma9_base]
    name: Push Alma9 g4.10.7 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/alma9-g4.10.7

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/alma9-g4.10.7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  alma9-g4-11-0:
    needs: [alma9_base]
    name: Push Alma9 g4.11.0 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/alma9-g4.11.0

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/alma9-g4.11.0
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  alma9-g4-11-1:
    needs: [alma9_base]
    name: Push Alma9 g4.11.1 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/alma9-g4.11.1

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/alma9-g4.11.1
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  alma9-g4-11-2:
    needs: [alma9_base]
    name: Push Alma9 g4.11.2 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/alma9-g4.11.2

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/alma9-g4.11.2
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}