name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build_docker_images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the centos7-base Docker image
      run: docker build . --file dockerfiles/centos7-base --tag centos7-base:$(date +%s)