name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu20_base:
    name: Push Ubuntu20 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Test Env
        run: |
          echo 'The GitHub Action Secret will be masked:  '
          echo ${{ secrets.BOOGERT_DOCKER_USERNAME }}
          echo 'Testing secret if its masked: '
          printenv

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        env:
          BOOGERT_DOCKER_USERNAME: ${{ secrets.BOOGERT_DOCKER_USERNAME }}
          BOOGERT_DOCKER_PASSWORD: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}
        with:
          username: ${{ secrets.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}