name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu20_base:
    name: Push Ubuntu20 docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.BOOGERT_DOCKER_USER_NAME }}
        run: |
          echo $SUPER_SECRET

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.boogert_docker_username }}
          password: ${{ secrets.boogert_docker_password }}



      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu22-base

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfiles/ubuntu22-base
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}